spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registerdemo?serverTimezone=GMT%2B8&useUnicode=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zhuge
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bocloud.register.vo
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true

